name: Start DDNet Server
on: workflow_dispatch

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DDNet
        run: |
          sudo apt update
          # Скачиваем DDNet (собираем из частей, чтобы не обрезалось)
          D_URL="https://ru.ddnet.org/downloads/DDNet-19.8-linux_x86_64.tar.xz"
          D_FILE="DDNet-19.8-linux_x86_64.tar.xz"
          curl -L "${D_URL}${D_FILE}" -o ddnet.tar.xz
          mkdir ddnet_temp
          tar -xvf ddnet.tar.xz -C ddnet_temp --strip-components=1
          cp -r ddnet_temp/* .
          chmod +x DDNet-Server

      - name: Setup Tunnel (Playit.gg)
        run: |
          # Используем твою ссылку на скрипт установки
          wget https://github.com/aBoredDev/playit-setup-script/archive/refs/heads/main.zip
          unzip main.zip
          cd playit-setup-script-main
          # Установка playit через их скрипт
          sudo chmod +x setup.sh
          sudo ./setup.sh
          
          # Запуск настройки. Ссылка появится в логах ниже!
          playit setup --secret_path .playit_secret &
          sleep 25
          
      - name: Run Server
        run: |
          ./DDNet-Server -f autoexec_server.cfg
