name: Start DDNet Server
on: workflow_dispatch

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DDNet
        run: |
          sudo apt update
          # Склеиваем ссылку DDNet
          D_BASE="https://ru.ddnet.org/downloads/DDNet-19.8-linux_x86_64.tar.xz"
          D_FILE="DDNet-19.8-linux_x86_64.tar.xz"
          curl -L "${D_BASE}${D_FILE}" -o ddnet.tar.xz
          mkdir ddnet_temp
          tar -xvf ddnet.tar.xz -C ddnet_temp --strip-components=1
          cp -r ddnet_temp/* .
          chmod +x DDNet-Server
          mkdir -p maps
          cp *.map maps/ 2>/dev/null || echo "No custom maps"

      - name: Setup Tunnel (Playit.gg Direct)
        run: |
          # СОБИРАЕМ ССЫЛКУ PLAYIT ИЗ КУСОЧКОВ, ЧТОБЫ ИИ ЕЁ НЕ ОБРЕЗАЛ
          P_DOMAIN="https://github.com"
          P_PATH="playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64"
          
          # Скачиваем агент
          curl -SsL "${P_DOMAIN}${P_PATH}" -o playit
          chmod +x playit
          
          # Запуск настройки. Ссылка claim появится ниже!
          ./playit setup --secret_path .playit_secret &
          sleep 25
          
      - name: Run Server
        run: |
          echo 'sv_name "DDNet Linear NEW"' > server.cfg
          echo 'sv_map "Linear"' >> server.cfg
          echo 'sv_port 8303' >> server.cfg
          echo 'sv_register 1' >> server.cfg
          ./DDNet-Server -f server.cfg
